### ISSUE TITLE
Function-like macros should ignore constant expansion

### ISSUE THREAD

**Issue by NotYourFox** [Lambosaurus/py-c-preprocessor#14]
As is shown by compilers such as OnlineGDB's C compiler, in the following code:
```c
#define MACRO(x) x
MACRO
```
`MACRO` in the second line is interpreted as an undeclared identifier, rather than an invalid macro expansion.

This test case, however, raises a "Macro ... expects arguments" exception
```python
p = Preprocessor()
p.define("MACRO_FUNC", "x", ["x"])
test_assert(p.expand("MACRO_FUNC(1)"), "1")
test_assert(p.expand("MACRO_FUNC"), "MACRO_FUNC")
```
whereas one would expect that the occurrence would simply be ignored and left "as is".

**Comment by Lambosaurus** [comment]
I believe I've fixed this. Notify me if this doesn't work on your own test cases.
