### ISSUE TITLE
Please specify a license

### ISSUE THREAD

**Issue by JonathonReinhart** [Lambosaurus/py-c-preprocessor#8]
Hi, cool project! I'm impressed with how easy it was to get started with your library.

There's currently no license specified in this codebase. Would you mind adding one? I recommend [Apache 2.0](https://choosealicense.com/licenses/apache-2.0/) or [MIT](https://choosealicense.com/licenses/mit/).

**Comment by Lambosaurus** [comment]
Thanks! I'm glad its useful.

I have included the MIT license here: 7c86627e5f6ff1cae202d224388158fda6b5f19e

**Comment by JonathonReinhart** [comment]
⚡ Thanks!
